# Metadata for the site header and footer
title: EPA LATAM
description: Sitio Web del Grupo de Enfermería de Práctica Avanzada de Latinoamérica

# Markdown parser and theme settings
markdown: kramdown
theme: jekyll-theme-cayman
